---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gpu-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nvidia
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: gpu-operator
  targetNamespace: nvidia-operator
